// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsFV61KGgURC3J3nRrS6me3niwktb4tbc',
    appId: '1:1069748773101:web:15231ead4aeed5d7ebace4',
    messagingSenderId: '1069748773101',
    projectId: 'maqsaf-2025',
    authDomain: 'maqsaf-2025.firebaseapp.com',
    storageBucket: 'maqsaf-2025.firebasestorage.app',
    measurementId: 'G-X17DC8QGC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA82_30L18eiE5-T9KHiJ21Xjx-9vY1egA',
    appId: '1:1069748773101:android:b5902750f476b8b7ebace4',
    messagingSenderId: '1069748773101',
    projectId: 'maqsaf-2025',
    storageBucket: 'maqsaf-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtiBC2K8Vp8pSz92QN4gFeiKA620JKAGQ',
    appId: '1:1069748773101:ios:822435128fa643edebace4',
    messagingSenderId: '1069748773101',
    projectId: 'maqsaf-2025',
    storageBucket: 'maqsaf-2025.firebasestorage.app',
    iosBundleId: 'com.example.maqsafApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtiBC2K8Vp8pSz92QN4gFeiKA620JKAGQ',
    appId: '1:1069748773101:ios:822435128fa643edebace4',
    messagingSenderId: '1069748773101',
    projectId: 'maqsaf-2025',
    storageBucket: 'maqsaf-2025.firebasestorage.app',
    iosBundleId: 'com.example.maqsafApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsFV61KGgURC3J3nRrS6me3niwktb4tbc',
    appId: '1:1069748773101:web:cc56454e812646a7ebace4',
    messagingSenderId: '1069748773101',
    projectId: 'maqsaf-2025',
    authDomain: 'maqsaf-2025.firebaseapp.com',
    storageBucket: 'maqsaf-2025.firebasestorage.app',
    measurementId: 'G-TYVKG4NM64',
  );
}
